In [ ]:
import torch
import numpy as np

In [ ]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)

In [ ]:
print(type(x_data))

<class 'torch.Tensor'>


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [ ]:
print(type(x_np))

<class 'torch.Tensor'>


In [ ]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [ ]:
print(x_rand)

tensor([[0.7955, 0.1859],
        [0.6172, 0.1900]])


In [ ]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)

tensor([[0.4115, 0.1439, 0.9403],
        [0.8079, 0.5783, 0.7393]])


In [ ]:
print(type(random_tensor))
ones_tensor = torch.ones(shape)

<class 'torch.Tensor'>


In [ ]:
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(type(ones_tensor))

<class 'torch.Tensor'>


In [ ]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(type(zeros_tensor))
tensor = torch.rand(3,4)

<class 'torch.Tensor'>


In [ ]:
print(tensor)

tensor([[0.2754, 0.8200, 0.7192, 0.9433],
        [0.7146, 0.8168, 0.6499, 0.0256],
        [0.0312, 0.9644, 0.6005, 0.5078]])


In [ ]:
tensor.shape

torch.Size([3, 4])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

In [ ]:
tensor = torch.ones(4,4)

In [ ]:
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [ ]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [ ]:
n = t.numpy()
print(n)
print(type(n))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
